### ISSUE TITLE
Support IP2Location LITE

### ISSUE THREAD

**Issue by m-cameron** [JuliaWeb/GeoIP.jl#10]
Do you support IP2Location LITE database?

http://lite.ip2location.com

**Comment by sbromberger** [comment]
No - the app currently uses MaxMind's geolocation database. It's certainly possible to add others, though, if you'd like to take a shot at it.

**Comment by randyzwitch** [comment]
As @sbromberger said, it's possible, but upon reading the website, I wonder which is more accurate and should we only provide one? The ip2location site is pretty upfront about the open source version being way less accurate than their paid version. I don't remember MaxMind being so aggressive in pointing that out (either through omission or the difference in the paid version being smaller)

**Comment by randyzwitch** [comment]
This has taken an odd turn of events. Closing as an "issue", but someone is free to submit the working code for submission and/or create another geolocation package. That's the fun of open-source :+1:

**Comment by sbromberger** [comment]
Just FYI - I'm going to tag a new version in the next couple of days to get tests passing and 0.4 readiness. No new functionality.
