### ISSUE TITLE
Use RemoteFiles.jl when it's registered

### ISSUE THREAD

**Issue by sbromberger** [JuliaWeb/GeoIP.jl#16]
https://github.com/helgee/RemoteFiles.jl

**Comment by Arkoniak** [comment]
It worth further consideration, since GeoLIte2 files, are not accessible anymore and simple download procedures are not going to work.

**Comment by Arkoniak** [comment]
I do not think that it makes sense to provide download capabilities, especially taking into account the fact, that `MaxMind` has its own GeoIP Updater. So, I close this issue, please reopen it or add new issue if such functionality is really needed.
