### ISSUE TITLE
Request to Maintain

### ISSUE THREAD

**Issue by nsmith5** [JuliaWeb/GeoIP.jl#18]
This package seems to have fallen off the radar a bit. I'd like write permissions to perform some updates and maintenance if possible (add appveyor, increase performance, complete some of @sbromberger 's ideas, write documentation etc).

**Comment by nsmith5** [comment]
cc @ararslan @jrevels @sbromberger @tanmaykm @WestleyArgentum

**Comment by sbromberger** [comment]
Fine by me. I don't quite know how to make it happen, though. Let me see if I can just grant you access.

**Comment by nsmith5** [comment]
Ok thanks!

**Comment by sbromberger** [comment]
Yup, I think that should do it. You should have an invitation to a team. Once you accept it you should have write access to the repo.

**Comment by nsmith5** [comment]
Thank!
