### ISSUE TITLE
Remove deprecated code from IPNets module

### ISSUE THREAD

**Issue by Arkoniak** [JuliaWeb/GeoIP.jl#42]
There are artifacts, which left from pre 0.7 era in `IPNets` module.

`Base: start, next, done` should be changed to a single `iterate`

**Comment by fredrikekre** [comment]
I just updated the IPNets.jl package for Juila 1.X and wanted to test it with this package. Perhaps after that has been merged this package can just use IPNets.jl as a regular dependency.

**Comment by Arkoniak** [comment]
Wow, this is awesome, as soon as it will be merged, I'll make necessary changes.

**Comment by Arkoniak** [comment]
Can you give a link to updated version? Last update of https://github.com/JuliaWeb/IPNets.jl is 3 years old.

**Comment by fredrikekre** [comment]
https://github.com/JuliaWeb/IPNets.jl/pull/17

**Comment by fredrikekre** [comment]
Merged and released as IPNets 1.0.0.

**Comment by Arkoniak** [comment]
Thank you, `IPNets.jl` used now in `0.5.0`.
