### ISSUE TITLE
ERROR: `geolocate` has no method matching geolocate(::Type{IPv4})

### ISSUE THREAD

**Issue by paulanalyst** [JuliaWeb/GeoIP.jl#8]
Version 0.3.6 (2015-02-17 22:12 UTC)
 Official http://julialang.org/ release
 x86_64-w64-mingw32

julia> Pkg.add("GeoIP")
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of DataArrays from git://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of DataFrames from git://github.com/JuliaStats/DataFrames.jl.git
INFO: Cloning cache of GZip from git://github.com/JuliaLang/GZip.jl.git
INFO: Cloning cache of GeoIP from git://github.com/JuliaWeb/GeoIP.jl.git
INFO: Cloning cache of IPNets from git://github.com/JuliaWeb/IPNets.jl.git
INFO: Cloning cache of Reexport from git://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SortingAlgorithms from git://github.com/JuliaLang/SortingAlgorithms.jl.git
INFO: Cloning cache of StatsBase from git://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of ZipFile from git://github.com/fhs/ZipFile.jl.git
INFO: Installing ArrayViews v0.4.8
INFO: Installing DataArrays v0.2.11
INFO: Installing DataFrames v0.6.1
INFO: Installing GZip v0.2.13
INFO: Installing GeoIP v0.2.0
INFO: Installing IPNets v0.1.3
INFO: Installing Reexport v0.0.2
INFO: Installing SortingAlgorithms v0.0.3
INFO: Installing StatsBase v0.6.12
INFO: Installing ZipFile v0.2.3
INFO: Building HttpParser
INFO: Building LibCURL
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repom
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repom
ml
INFO: Building Nettle
INFO: Building GnuTLS
INFO: Package database updated

julia> using GeoIP
Warning: using StatsBase.midpoints in module Main conflicts with an existing identifier.
Warning: using StatsBase.histrange in module Main conflicts with an existing identifier.

julia> GeoIP.geolocate(IPv4)
ERROR: `geolocate` has no method matching geolocate(::Type{IPv4})

julia> GeoIP.geolocate(IPv6)
ERROR: `geolocate` has no method matching geolocate(::Type{IPv6})

julia> a = ip"1.2.3.4"
ip"1.2.3.4"

julia> geolocate(a)
ERROR: type Response has no field data
 in geolocate at C:\Users\SAMSUNG2\.julia\v0.3\GeoIP\src\geoip-module.jl:126

julia>

Paul

**Comment by sbromberger** [comment]
The last attempt (`geolocate(ip"1.2.3.4")`) is the correct syntax. `geolocate` doesn't take a datatype, it takes an instance of `IPv4`. 

In any case, the problem appears to be with HttpParser.jl when GeoIP tries to download new copies of the Maxmind data:

```
julia> geolocate(a, noupdate=false)
INFO: Geolocation data is out of date. Updating...
ERROR: HTTP Parser Exception: HPE_INVALID_EOF_STATE(9):stream ended at an unexpected time
 in http_parser_execute at /Users/seth/.julia/v0.3/HttpParser/src/HttpParser.jl:110
 in process_response at /Users/seth/.julia/v0.3/Requests/src/Requests.jl:237
 in do_request at /Users/seth/.julia/v0.3/Requests/src/Requests.jl:569
 in get at /Users/seth/.julia/v0.3/Requests/src/Requests.jl:583
 in get at /Users/seth/.julia/v0.3/Requests/src/Requests.jl:582
 in dldata at /Users/seth/.julia/v0.3/GeoIP/src/geoip-module.jl:50
 in update at /Users/seth/.julia/v0.3/GeoIP/src/geoip-module.jl:90
 in geolocate at /Users/seth/.julia/v0.3/GeoIP/src/geoip-module.jl:128
```

I'm not terribly surprised given the fragility of Requests.jl and the web stack these days, but I'll try to dig deeper this weekend.

**Comment by sbromberger** [comment]
PS: you need internet connectivity, of course.

**Comment by sbromberger** [comment]
Wait - no. Does Requests on windows use HTTPClient? That Response object is part of libcurl, not Requests.

**Comment by sbromberger** [comment]
@paulanalyst can you do a Pkg.checkout("GeoIP","libcurl") and let me know whether that works? Thanks.

**Comment by paulanalyst** [comment]
bingo, somthing wrong :/

julia> Pkg.checkout("GeoIP","libcurl")
INFO: Checking out GeoIP libcurl...
fatal: Cannot update paths and switch to branch 'libcurl' at the same time.
Did you intend to checkout 'origin/libcurl' which can not be resolved as 
commit?
ERROR: failed process: Process(`git 
'--work-tree=C:\Users\SAMSUNG2\.julia\v0.3\GeoIP' 
'--git-dir=C:\Users\SAMSUNG2
\.julia\v0.3\GeoIP\.git' checkout -q -B libcurl -t origin/libcurl`, 
ProcessExited(128)) [128]
  in error at error.jl:22 (repeats 2 times)

julia>


Paul

W dniu 2015-02-28 o 18:05, Seth Bromberger pisze:

**Comment by sbromberger** [comment]
Try doing a `Pkg.update()` first.

I still don't know why your installation is using libcurl instead of Requests.jl. That's very strange.

**Comment by paulanalyst** [comment]
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using GeoIP

julia> GeoIP.geolocate(IPv4)
ERROR: `geolocate` has no method matching geolocate(::Type{IPv4})

julia> a = ip"1.2.3.4"
ip"1.2.3.4"

julia> geolocate(a)
WARNING: Geolocation data is out of date. Consider updating.
INFO: Geolocation data not in memory. Loading...
ERROR: Geolocation data cannot be read. Consider updating.
  in load at C:\Users\SAMSUNG2\.julia\v0.3\GeoIP\src\geoip-module.jl:105
  in geolocate at 
C:\Users\SAMSUNG2\.julia\v0.3\GeoIP\src\geoip-module.jl:136

julia> geolocate(a, noupdate=false)
INFO: Geolocation data is out of date. Updating...
ERROR: HTTP Parser Exception: HPE_INVALID_EOF_STATE(9):stream ended at 
an unexpected time
  in http_parser_execute at 
C:\Users\SAMSUNG2\.julia\v0.3\HttpParser\src\HttpParser.jl:110 (repeats 
2 times)

julia>

Paul
W dniu 2015-02-28 o 18:15, Seth Bromberger pisze:

**Comment by sbromberger** [comment]
I'm stumped. We just switched you over to HTTPClient, which doesn't use HttpParser at all.

**Comment by sbromberger** [comment]
No - wait. You forgot to do the Pkg.checkout after you did Pkg.update.

**Comment by sbromberger** [comment]
I can confirm that this works on a clean build.

```
seth@snoopy:~/.julia/v0.4$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3105 (2015-02-03 22:17 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4b41ae6 (24 days old master)
|__/                   |  x86_64-apple-darwin14.1.0

julia> Pkg.add("GeoIP")
INFO: Cloning cache of GeoIP from git://github.com/JuliaWeb/GeoIP.jl.git
INFO: Installing GeoIP v0.2.0
INFO: Removing HTTPClient v0.1.4
INFO: Removing LibCURL v0.1.5
INFO: Building HttpParser

WARNING: deprecated syntax "[a=>b, ...]" at /Users/seth/.julia/v0.4/HttpParser/deps/build.jl:42.
Use "Dict(a=>b, ...)" instead.
INFO: Building Homebrew
HEAD is now at b6f57cd typesafe-activator 1.3.2
HEAD is now at d3dcfbb Tweak inreplace rules a little so we don't fail on them
INFO: Building Nettle

WARNING: deprecated syntax "[a=>b, ...]" at /Users/seth/.julia/v0.4/Nettle/deps/build.jl:39.
Use "Dict(a=>b, ...)" instead.
INFO: Building GnuTLS

WARNING: deprecated syntax "{a=>b, ...}" at /Users/seth/.julia/v0.4/GnuTLS/deps/build.jl:15.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /Users/seth/.julia/v0.4/GnuTLS/deps/build.jl:48.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /Users/seth/.julia/v0.4/GnuTLS/deps/build.jl:53.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /Users/seth/.julia/v0.4/GnuTLS/deps/build.jl:55.
Use "Dict(a=>b, ...)" instead.
INFO: Package database updated

julia> Pkg.checkout("GeoIP","libcurl")
INFO: Checking out GeoIP libcurl...
INFO: Pulling GeoIP latest libcurl...
INFO: Installing HTTPClient v0.1.4
INFO: Installing LibCURL v0.1.5
INFO: Building LibCURL

julia> using GeoIP

julia> GeoIP.getmd5()
"99b14f811805ec350ddd952a4631b876"

julia> Geo^C

julia> a = 10
10

julia> a = ip"1.2.3.4"
ip"1.2.3.4"

julia> geolocate(a)
WARNING: Geolocation data is out of date. Consider updating.
INFO: Geolocation data not in memory. Loading...
ERROR: Geolocation data cannot be read. Consider updating.
 in load at /Users/seth/.julia/v0.4/GeoIP/src/geoip-module.jl:109
 in geolocate at /Users/seth/.julia/v0.4/GeoIP/src/geoip-module.jl:140

julia> geolocate(a,noupdate=false)
INFO: Geolocation data is out of date. Updating...
INFO: Geolocation data not in memory. Loading...
Dict{Symbol,Union(DataArrays.NAtype,AbstractString,Integer,IPNets.IPv4Net,GeoIP.Location)} with 17 entries:
  :v4net                   => IPNets.IPv4Net("1.2.3.0/24")
  :metro_code              => 819
  :time_zone               => "America/Los_Angeles"
  :location                => GeoIP.Location(-122.3042,47.913,0.0,"WGS84")
  :country_iso_code        => "US"
  :city_name               => "Mukilteo"
  :subdivision_1_iso_code  => "WA"
  :subdivision_2_iso_code  => NA
  :subdivision_1_name      => "Washington"
  :postal_code             => "98275"
  :continent_code          => NA
  :country_name            => "United States"
  :locale_code             => "en"
  :continent_name          => "North America"
  :subdivision_2_name      => NA
  :geoname_id              => 5804306
  :registered_country_geo… => 2077456
```

**Comment by paulanalyst** [comment]
Restart julia and:
|               _
    _       _ _(_)_     |  A fresh approach to technical computing
   (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
    _ _   _| |_  __ _   |  Type "help()" for help.
   | | | | | | |/ _` |  |
   | | |_| | | | (_| |  |  Version 0.3.6 (2015-02-17 22:12 UTC)
  _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using GeoIP
WARNING: This version of the GnuTLS library (3.2.15) is deprecated
and contains known security vulnerabilities. Please upgrade to a
more recent version.

julia> geolocate(a, noupdate=false)
ERROR: a not defined

julia> a = ip"1.2.3.4"
ip"1.2.3.4"

julia> geolocate(a, noupdate=false)
INFO: Geolocation data is out of date. Updating...
ERROR: HTTP Parser Exception: HPE_INVALID_EOF_STATE(9):stream ended at 
an unexpected time
  in http_parser_execute at 
C:\Users\SAMSUNG2\.julia\v0.3\HttpParser\src\HttpParser.jl:110 (repeats 
2 times)

julia> Pkg.rm("GnuTLS")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.checkout("GeoIP","libcurl")
INFO: Checking out GeoIP libcurl...
fatal: Cannot update paths and switch to branch 'libcurl' at the same time.
Did you intend to checkout 'origin/libcurl' which can not be resolved as 
commit?
ERROR: failed process: Process(`git 
'--work-tree=C:\Users\SAMSUNG2\.julia\v0.3\GeoIP' 
'--git-dir=C:\Users\SAMSUNG2
\.julia\v0.3\GeoIP\.git' checkout -q -B libcurl -t origin/libcurl`, 
ProcessExited(128)) [128]
  in error at error.jl:22 (repeats 2 times)

julia> Pkg.add("GnuTLS")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.checkout("GeoIP","libcurl")
INFO: Checking out GeoIP libcurl...
fatal: Cannot update paths and switch to branch 'libcurl' at the same time.
Did you intend to checkout 'origin/libcurl' which can not be resolved as 
commit?
ERROR: failed process: Process(`git 
'--work-tree=C:\Users\SAMSUNG2\.julia\v0.3\GeoIP' 
'--git-dir=C:\Users\SAMSUNG2
\.julia\v0.3\GeoIP\.git' checkout -q -B libcurl -t origin/libcurl`, 
ProcessExited(128)) [128]
  in error at error.jl:22 (repeats 2 times)

julia>

Paul
|W dniu 2015-02-28 o 18:26, Seth Bromberger pisze:

**Comment by sbromberger** [comment]
OK, let's simplify: why are you checking out all those packages?

Do this: Pkg.rm("GeoIP"), make sure that it's removed from caches and your filesystem, restart julia, do a Pkg.add("GeoIP"), then a Pkg.checkout("GeoIP","libcurl"), and let me know whether that works.

**Comment by paulanalyst** [comment]
After:
Pkg.rm("GeoIP")
exit julia
restart win
remove .cash dir in julia

                _
    _       _ _(_)_     |  A fresh approach to technical computing
   (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
    _ _   _| |_  __ _   |  Type "help()" for help.
   | | | | | | |/ _` |  |
   | | |_| | | | (_| |  |  Version 0.3.6 (2015-02-17 22:12 UTC)
  _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("GeoIP")
INFO: Cloning cache of ArrayViews from 
git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of DataArrays from 
git://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of DataFrames from 
git://github.com/JuliaStats/DataFrames.jl.git
INFO: Cloning cache of GZip from git://github.com/JuliaLang/GZip.jl.git
INFO: Cloning cache of GeoIP from git://github.com/JuliaWeb/GeoIP.jl.git
INFO: Cloning cache of IPNets from git://github.com/JuliaWeb/IPNets.jl.git
INFO: Cloning cache of Reexport from 
git://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SortingAlgorithms from 
git://github.com/JuliaLang/SortingAlgorithms.jl.git
INFO: Cloning cache of StatsBase from 
git://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of ZipFile from git://github.com/fhs/ZipFile.jl.git
INFO: Installing ArrayViews v0.4.8
INFO: Installing DataArrays v0.2.11
INFO: Installing DataFrames v0.6.1
INFO: Installing GZip v0.2.13
INFO: Installing GeoIP v0.2.0
INFO: Installing IPNets v0.1.3
INFO: Installing Reexport v0.0.2
INFO: Installing SortingAlgorithms v0.0.3
INFO: Installing StatsBase v0.6.12
INFO: Installing ZipFile v0.2.3
INFO: Building HttpParser
INFO: Building LibCURL
INFO: Updating WinRPM package list
INFO: Downloading 
http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading 
http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Building WinRPM
INFO: Downloading 
http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading 
http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Building Nettle
INFO: Building GnuTLS
INFO: Package database updated

julia> using GnuTLS
WARNING: This version of the GnuTLS library (3.2.15) is deprecated
and contains known security vulnerabilities. Please upgrade to a
more recent version.

julia>

julia> sess = GnuTLS.Session()
Session(Ptr{Void} @0x0000000005f83fe0,false,#undef,#undef)

julia> set_priority_string!(sess)

julia> set_credentials!(sess,GnuTLS.CertificateStore())

julia> associate_stream(sess,connect("github.com",443))

julia> handshake!(sess)

julia> write(sess,"GET / HTTP/1.1\r\n\r\n")
18

julia> print(readall(sess))
Uint8[]
julia> Pkg.checkout("GeoIP","libcurl")
INFO: Checking out GeoIP libcurl...
INFO: Pulling GeoIP latest libcurl...
INFO: No packages to install, update or remove

julia> using GeoIP

julia>  GeoIP.getmd5()
"99b14f811805ec350ddd952a4631b876"

julia> a = ip"1.2.3.4"
ip"1.2.3.4"

julia> geolocate(a)
WARNING: Geolocation data is out of date. Consider updating.
INFO: Geolocation data not in memory. Loading...
ERROR: Geolocation data cannot be read. Consider updating.
  in load at C:\Users\SAMSUNG2\.julia\v0.3\GeoIP\src\geoip-module.jl:109
  in geolocate at 
C:\Users\SAMSUNG2\.julia\v0.3\GeoIP\src\geoip-module.jl:140

julia>

Paul

W dniu 2015-02-28 o 18:34, Seth Bromberger pisze:

**Comment by sbromberger** [comment]
Let's keep the gnutls warning separate from the geoip issue. That said, so
far so good. Now update the geoip data via geolocate(a, noupdate=false) and
let me know whether that works.




On Feb 28, 2015, at 09:48, paulanalyst <notifications@github.com> wrote:

After:
Pkg.rm("GeoIP")
exit julia
restart win
remove .cash dir in julia

_
_ _ _(_)_ | A fresh approach to technical computing
(_) | (_) (_) | Documentation: http://docs.julialang.org
_ _ _| |_ __ _ | Type "help()" for help.
| | | | | | |/ _` | |
| | |_| | | | (_| | | Version 0.3.6 (2015-02-17 22:12 UTC)
_/ |\__'_|_|_|\__'_| | Official http://julialang.org/ release
|__/ | x86_64-w64-mingw32

julia> Pkg.add("GeoIP")
INFO: Cloning cache of ArrayViews from
git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of DataArrays from
git://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of DataFrames from
git://github.com/JuliaStats/DataFrames.jl.git
INFO: Cloning cache of GZip from git://github.com/JuliaLang/GZip.jl.git
INFO: Cloning cache of GeoIP from git://github.com/JuliaWeb/GeoIP.jl.git
INFO: Cloning cache of IPNets from git://github.com/JuliaWeb/IPNets.jl.git
INFO: Cloning cache of Reexport from
git://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SortingAlgorithms from
git://github.com/JuliaLang/SortingAlgorithms.jl.git
INFO: Cloning cache of StatsBase from
git://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of ZipFile from git://github.com/fhs/ZipFile.jl.git
INFO: Installing ArrayViews v0.4.8
INFO: Installing DataArrays v0.2.11
INFO: Installing DataFrames v0.6.1
INFO: Installing GZip v0.2.13
INFO: Installing GeoIP v0.2.0
INFO: Installing IPNets v0.1.3
INFO: Installing Reexport v0.0.2
INFO: Installing SortingAlgorithms v0.0.3
INFO: Installing StatsBase v0.6.12
INFO: Installing ZipFile v0.2.3
INFO: Building HttpParser
INFO: Building LibCURL
INFO: Updating WinRPM package list
INFO: Downloading
http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading
http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Building WinRPM
INFO: Downloading
http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading
http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Building Nettle
INFO: Building GnuTLS
INFO: Package database updated

julia> using GnuTLS
WARNING: This version of the GnuTLS library (3.2.15) is deprecated
and contains known security vulnerabilities. Please upgrade to a
more recent version.

julia>

julia> sess = GnuTLS.Session()
Session(Ptr{Void} @0x0000000005f83fe0,false,#undef,#undef)

julia> set_priority_string!(sess)

julia> set_credentials!(sess,GnuTLS.CertificateStore())

julia> associate_stream(sess,connect("github.com",443))

julia> handshake!(sess)

julia> write(sess,"GET / HTTP/1.1\r\n\r\n")
18

julia> print(readall(sess))
Uint8[]
julia> Pkg.checkout("GeoIP","libcurl")
INFO: Checking out GeoIP libcurl...
INFO: Pulling GeoIP latest libcurl...
INFO: No packages to install, update or remove

julia> using GeoIP

julia> GeoIP.getmd5()
"99b14f811805ec350ddd952a4631b876"

julia> a = ip"1.2.3.4"
ip"1.2.3.4"

julia> geolocate(a)
WARNING: Geolocation data is out of date. Consider updating.
INFO: Geolocation data not in memory. Loading...
ERROR: Geolocation data cannot be read. Consider updating.
in load at C:\Users\SAMSUNG2\.julia\v0.3\GeoIP\src\geoip-module.jl:109
in geolocate at
C:\Users\SAMSUNG2\.julia\v0.3\GeoIP\src\geoip-module.jl:140

julia>

Paul

W dniu 2015-02-28 o 18:34, Seth Bromberger pisze:
>
> OK, let's simplify: why are you checking out all those packages?
>
> Do this: Pkg.rm("GeoIP"), make sure that it's removed from caches and
> your filesystem, restart julia, do a Pkg.add("GeoIP"), then a
> Pkg.checkout("GeoIP","libcurl"), and let me know whether that works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaWeb/GeoIP.jl/issues/8#issuecomment-76536131>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/JuliaWeb/GeoIP.jl/issues/8#issuecomment-76536807>.

**Comment by paulanalyst** [comment]
Works, big thx:)
julia> geolocate(a, noupdate=false)
INFO: Geolocation data is out of date. Updating...
INFO: Geolocation data not in memory. Loading...
Dict{Symbol,Union(Integer,Location,IPv4Net,NAtype,String)} with 17 entries:
   :v4net                         => IPv4Net("1.2.3.0/24")
   :metro_code                    => 819
   :time_zone                     => "America/Los_Angeles"
   :location                      => Location(-122.3042,47.913,0.0,"WGS84")
   :country_iso_code              => "US"
   :city_name                     => "Mukilteo"
   :subdivision_1_iso_code        => "WA"
   :subdivision_2_iso_code        => NA
   :subdivision_1_name            => "Washington"
   :postal_code                   => "98275"
   :continent_code                => NA
   :country_name                  => "United States"
   :locale_code                   => "en"
   :continent_name                => "North America"
   :subdivision_2_name            => NA
   :geoname_id                    => 5804306
   :registered_country_geoname_id => 2077456

julia>

Paul
W dniu 2015-02-28 o 18:56, Seth Bromberger pisze:
> Let's keep the gnutls warning separate from the geoip issue. That said, so
> far so good. Now update the geoip data via geolocate(a, 
> noupdate=false) and
> let me know whether that works.
>
>
>
>
